CREATE TABLE IF NOT EXISTS athletes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  athlete_code VARCHAR(20) NOT NULL UNIQUE,
  full_name VARCHAR(150) NOT NULL,
  gender ENUM('male', 'female', 'other') NOT NULL,
  date_of_birth DATE NOT NULL,
  passport_number VARCHAR(50) NOT NULL,
  sport VARCHAR(100) NOT NULL,
  team_federation VARCHAR(150),
  destination_country VARCHAR(100) NOT NULL,
  destination_city VARCHAR(100),
  competition_name VARCHAR(200) NOT NULL,
  purpose_of_travel VARCHAR(200),
  visa_type VARCHAR(100),
  embassy VARCHAR(150),
  departure_date DATE NOT NULL,
  return_date DATE NOT NULL,
  assigned_officer_id INT,
  priority ENUM('high', 'medium', 'low') NOT NULL DEFAULT 'medium',
  notes TEXT,
  progress_percent INT NOT NULL DEFAULT 0,
  status ENUM('new', 'preparing_documents', 'in_progress', 'almost_ready', 'ready_for_travel')
    NOT NULL DEFAULT 'new',
  created_by INT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  FOREIGN KEY (assigned_officer_id) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_athletes_status (status),
  INDEX idx_athletes_destination (destination_country),
  INDEX idx_athletes_departure (departure_date),
  INDEX idx_athletes_deleted (deleted_at)
) ENGINE=InnoDB;
